name: 'Release Hash Certification'
description: 'Generates a hash of the release and certifies it using the TrustOS API'
inputs:
  api_user:
    description: 'TrustOS API user'
    required: true
  api_password:
    description: 'TrustOS API password'
    required: true
  directory:
    description: 'Directory to certify'
    default: '.'
    required: false
  env: 
    description: 'TrustOS environment (lab/prod)'
    default: 'lab'
    required: false
outputs:
  token:
    description: 'Id api jwt'
  commit_author:
    description: 'Author of the last commit'
  commit_date:
    description: 'Date of the last commit'
  hash:
    description: 'Generated hash of the release'
  certification_id:
    description: 'Certification ID returned by the API'
runs:
  using: 'node20'
  main: 'dist/index.js'
