name: Test Action
on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./  # Esto usa la action del directorio actual
        with:
          api_user: ${{ secrets.API_USER }}
          api_password: ${{ secrets.API_PASSWORD }}

      - name: Check Output
        run: |
          echo "Token received: ${{ steps.test.outputs.token }}"
