name: Create Certificate

on:
  workflow_dispatch:

jobs:
  create-certificate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Certificate
        run: |
          chmod +x ./create_certificate.sh
          ./create_certificate.sh \
            "${{ secrets.TRUSTOS_USERNAME }}" \
            "${{ secrets.TRUSTOS_PASSWORD }}" \
            "${{ secrets.TRUSTOS_SECRET }}" \
            "${{ github.actor }}" \
            "${{ github.sha }}"
